---
# hosts entries for the controller server on localhost to circumvent firewall issues
hosts_hostname: "{{ _domain_name }}"
hosts_entries:
  - name: "{{ _domain_name }}"
    ip: 127.0.0.1
    aliases:
      - "gitlab.{{ _domain_name }}"
