---
# Default set of SGs for standalone EC2 machines
_security_groups:
  - common_network
  - ssh_open # configure ssh_restricted with the correct IP address(es) and use instead
  #- ssh_restricted # fix IP addresses before uncommenting these
  #- wazuh_outbound

# For convenience ce-provision ships with an optional list of common security groups called _security_groups_defaults.
# In this example you will find a list of custom security groups called _my_security_groups_defaults.
# This _all_security_groups variable is used in hosts/group_vars/all/aws_vpc.yml to create the security groups required.
# It allows us to join the default groups with our custom groups and have them all created at once.
_all_security_groups: "{{ _security_groups_defaults + _my_security_groups_defaults }}"

# My custom security groups.
# This is a list of reusable security groups that are unique to this controller.
_my_security_groups_defaults:
  - "{{ _common_security_groups.prometheus_server }}"
  #- "{{ _common_security_groups.ssh_restricted }}" # fix IP addresses before uncommenting
  #- "{{ _common_security_groups.wazuh_outbound }}"

_my_security_groups:
  ssh_restricted:
    name: ssh_restricted
    description: Allow specific incoming traffic on port 22.
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: "X.X.X.X/32"
        rule_desc: Allow incoming traffic on port 22 from this address.
  prometheus_server:
    name: prometheus_server
    description: Allow outbound traffic from Prometheus to scrapers.
    rules_egress:
      - proto: tcp
        ports:
          - 9100 # node exporter
          - 9101 # process exporter
        cidr_ip: "0.0.0.0/0"
        rule_desc: "Allow outbound traffic from Prometheus for scraping."
  wazuh_outbound:
    name: wazuh_outbound
    description: Allow traffic from client Wazuh configurations.
    rules_egress:
      - proto: tcp
        ports:
          - 1514 # ossec
          - 1515 # ossec
          - 55000 # wazuh dashboard
        cidr_ip: "X.X.X.X/32" # Change this to Wazuh server IP
        rule_desc: "Allow outbound traffic to Wazuh for vulnerability monitoring."
