---
# Be sure to update the IP address list at the end
aws_acl:
  - name: "{{ _infra_name }}_main_acl"
    description: "ACL rules from ce-provision-config"
    scope: CLOUDFRONT # Can be REGIONAL for ALBs
    region: "us-east-1"
    tags: "{{ _aws_tags }}"
    recreate: true
    rules:
      ip_sets:
        - rule_name: "Allowed-IPs-rule"
          set_name: "Allowed-IPs-set"
          description: "List of IPs from our VPNs - Ansible managed"
          action: allow
          priority: 1
          list:
            - X.X.X.X/32 # Change this to a list of your permitted IP addresses
