---
# Creates a default AWS ACL required by WAF and CloudFront
aws_acl:
  - name: "{{ _infra_name }}_main_acl"
    description: "ACL rules from ce-provision-config"
    scope: CLOUDFRONT # Can be REGIONAL for ALBs
    region: "us-east-1"
    tags: "{{ _aws_tags }}"
    recreate: true
# For information on default rulesets and configurations avaiable see the docs:
# https://codeenigma.github.io/ce-provision-docs/2.x/roles/aws/aws_acl/
