---
# Default AWS VPC configuration
aws_vpc:
  name: "{{ _infra_name }}"
  assign_instances_ipv6: false
  security_groups: "{{ _all_security_groups }}" # override the _security_groups_defaults list with a new list including our custom groups
  tags:
    Name: "{{ _aws_resource_name | default(omit) }}"
    Profile: "{{ _profile | default(omit) }}"
    Env: core
    Billing: "{{ _aws_billing_type | default(omit) }}"
    Infra: "{{ _infra_name | default(omit) }}"
    Ansible: managed
