---
# Default infra controller user
# You may need to set the correct server hostname in the path to the SSH keys for new servers
# Depending on how it was built it may not be localhost
user_provision:
  username: "{{ _ce_provision_username }}"
  groups:
    - bypass2fa
  ssh_keys:
    - "{{ lookup('file', '{{ _ce_provision_data_dir }}/localhost/home/controller/.ssh/id_ed25519.pub') }}"
